namespace AmazingAdventures
{
    partial class Form1
    {
        /// <summary>
        /// Обязательная переменная конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Освободить все используемые ресурсы.
        /// </summary>
        /// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Код, автоматически созданный конструктором форм Windows

        /// <summary>
        /// Требуемый метод для поддержки конструктора — не изменяйте 
        /// содержимое этого метода с помощью редактора кода.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.timer_moving = new System.Windows.Forms.Timer(this.components);
            this.imageListGame = new System.Windows.Forms.ImageList(this.components);
            this.imageListSymbols = new System.Windows.Forms.ImageList(this.components);
            this.menu_timer = new System.Windows.Forms.Timer(this.components);
            this.imgListValues = new System.Windows.Forms.ImageList(this.components);
            this.imgUI = new System.Windows.Forms.ImageList(this.components);
            this.imgUI_EnergyPoints = new System.Windows.Forms.ImageList(this.components);
            this.imgHeroValues = new System.Windows.Forms.ImageList(this.components);
            this.imgListInventory = new System.Windows.Forms.ImageList(this.components);
            this.imgListHeroWater = new System.Windows.Forms.ImageList(this.components);
            this.imgListInterface = new System.Windows.Forms.ImageList(this.components);
            this.imgListStone = new System.Windows.Forms.ImageList(this.components);
            this.imgForBuilding = new System.Windows.Forms.ImageList(this.components);
            this.imgListRoom = new System.Windows.Forms.ImageList(this.components);
            this.imgListEnemy = new System.Windows.Forms.ImageList(this.components);
            this.imgListBow = new System.Windows.Forms.ImageList(this.components);
            this.imgListItems = new System.Windows.Forms.ImageList(this.components);
            this.imgListEnemyAttack = new System.Windows.Forms.ImageList(this.components);
            this.imgHeroUnderDamage = new System.Windows.Forms.ImageList(this.components);
            this.imgListEnemyStrongAttack = new System.Windows.Forms.ImageList(this.components);
            this.imgHeroUseShovel = new System.Windows.Forms.ImageList(this.components);
            this.imgCoinValues = new System.Windows.Forms.ImageList(this.components);
            this.imgWateringStump = new System.Windows.Forms.ImageList(this.components);
            this.SuspendLayout();
            // 
            // timer_moving
            // 
            this.timer_moving.Interval = 170;
            this.timer_moving.Tick += new System.EventHandler(this.timer_moving_Tick);
            // 
            // imageListGame
            // 
            this.imageListGame.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageListGame.ImageStream")));
            this.imageListGame.TransparentColor = System.Drawing.Color.Transparent;
            this.imageListGame.Images.SetKeyName(0, "main_grass_1.png");
            this.imageListGame.Images.SetKeyName(1, "main_tree_1.png");
            this.imageListGame.Images.SetKeyName(2, "hero_down_stand.png");
            this.imageListGame.Images.SetKeyName(3, "hero_up_stand.png");
            this.imageListGame.Images.SetKeyName(4, "hero_left_stand.png");
            this.imageListGame.Images.SetKeyName(5, "hero_right_stand.png");
            this.imageListGame.Images.SetKeyName(6, "hero_down_1.png");
            this.imageListGame.Images.SetKeyName(7, "hero_down_2.png");
            this.imageListGame.Images.SetKeyName(8, "hero_down_3.png");
            this.imageListGame.Images.SetKeyName(9, "hero_down_4.png");
            this.imageListGame.Images.SetKeyName(10, "hero_down_stand_edle_1.png");
            this.imageListGame.Images.SetKeyName(11, "hero_down_stand_edle_2.png");
            this.imageListGame.Images.SetKeyName(12, "hero_up_1.png");
            this.imageListGame.Images.SetKeyName(13, "hero_up_2.png");
            this.imageListGame.Images.SetKeyName(14, "hero_up_3.png");
            this.imageListGame.Images.SetKeyName(15, "hero_up_4.png");
            this.imageListGame.Images.SetKeyName(16, "hero_left_1.png");
            this.imageListGame.Images.SetKeyName(17, "hero_left_2.png");
            this.imageListGame.Images.SetKeyName(18, "hero_left_3.png");
            this.imageListGame.Images.SetKeyName(19, "hero_left_4.png");
            this.imageListGame.Images.SetKeyName(20, "hero_right_1.png");
            this.imageListGame.Images.SetKeyName(21, "hero_right_2.png");
            this.imageListGame.Images.SetKeyName(22, "hero_right_3.png");
            this.imageListGame.Images.SetKeyName(23, "hero_right_4.png");
            this.imageListGame.Images.SetKeyName(24, "hero_attack_1.png");
            this.imageListGame.Images.SetKeyName(25, "hero_attack_2.png");
            this.imageListGame.Images.SetKeyName(26, "hero_attack_3.png");
            this.imageListGame.Images.SetKeyName(27, "hero_attack_4.png");
            this.imageListGame.Images.SetKeyName(28, "hero_attack_up_1.png");
            this.imageListGame.Images.SetKeyName(29, "hero_attack_up_2.png");
            this.imageListGame.Images.SetKeyName(30, "hero_attack_up_3.png");
            this.imageListGame.Images.SetKeyName(31, "hero_attack_up_4.png");
            this.imageListGame.Images.SetKeyName(32, "hero_attack_left_1.png");
            this.imageListGame.Images.SetKeyName(33, "hero_attack_left_2.png");
            this.imageListGame.Images.SetKeyName(34, "hero_attack_left_3.png");
            this.imageListGame.Images.SetKeyName(35, "hero_attack_left_4.png");
            this.imageListGame.Images.SetKeyName(36, "hero_attack_right_1.png");
            this.imageListGame.Images.SetKeyName(37, "hero_attack_right_2.png");
            this.imageListGame.Images.SetKeyName(38, "hero_attack_right_3.png");
            this.imageListGame.Images.SetKeyName(39, "hero_attack_right_4.png");
            this.imageListGame.Images.SetKeyName(40, "stump_tree_0.png");
            this.imageListGame.Images.SetKeyName(41, "tree_health_10.png");
            this.imageListGame.Images.SetKeyName(42, "tree_health_20.png");
            this.imageListGame.Images.SetKeyName(43, "tree_health_30.png");
            this.imageListGame.Images.SetKeyName(44, "tree_health_40.png");
            this.imageListGame.Images.SetKeyName(45, "tree_health_55.png");
            this.imageListGame.Images.SetKeyName(46, "tree_health_70.png");
            this.imageListGame.Images.SetKeyName(47, "tree_health_85.png");
            this.imageListGame.Images.SetKeyName(48, "tree_health_100_1.png");
            this.imageListGame.Images.SetKeyName(49, "stump_tree_1.png");
            this.imageListGame.Images.SetKeyName(50, "stump_tree_2.png");
            this.imageListGame.Images.SetKeyName(51, "stump_tree_3.png");
            this.imageListGame.Images.SetKeyName(52, "stump_tree_4.png");
            this.imageListGame.Images.SetKeyName(53, "stump_tree_5.png");
            this.imageListGame.Images.SetKeyName(54, "stump_tree_6.png");
            this.imageListGame.Images.SetKeyName(55, "stump_tree_7.png");
            this.imageListGame.Images.SetKeyName(56, "stump_tree_8.png");
            this.imageListGame.Images.SetKeyName(57, "stump_tree_9.png");
            this.imageListGame.Images.SetKeyName(58, "stump_tree_10.png");
            this.imageListGame.Images.SetKeyName(59, "stump_tree_11.png");
            this.imageListGame.Images.SetKeyName(60, "stump_tree_12.png");
            this.imageListGame.Images.SetKeyName(61, "stump_tree_13.png");
            this.imageListGame.Images.SetKeyName(62, "stump_tree_14.png");
            this.imageListGame.Images.SetKeyName(63, "stump_tree_15.png");
            this.imageListGame.Images.SetKeyName(64, "stump_tree_16.png");
            this.imageListGame.Images.SetKeyName(65, "stump_tree_17.png");
            this.imageListGame.Images.SetKeyName(66, "main_river.png");
            this.imageListGame.Images.SetKeyName(67, "river_center_bottom.png");
            this.imageListGame.Images.SetKeyName(68, "river_center_top.png");
            this.imageListGame.Images.SetKeyName(69, "river_left_bottom.png");
            this.imageListGame.Images.SetKeyName(70, "river_left_bottom_edge.png");
            this.imageListGame.Images.SetKeyName(71, "river_left_middle.png");
            this.imageListGame.Images.SetKeyName(72, "river_left_top.png");
            this.imageListGame.Images.SetKeyName(73, "river_left_top_edge.png");
            this.imageListGame.Images.SetKeyName(74, "river_right_bottom.png");
            this.imageListGame.Images.SetKeyName(75, "river_right_bottom_edge.png");
            this.imageListGame.Images.SetKeyName(76, "river_right_middle.png");
            this.imageListGame.Images.SetKeyName(77, "river_right_top.png");
            this.imageListGame.Images.SetKeyName(78, "river_right_top_edge.png");
            this.imageListGame.Images.SetKeyName(79, "main_river.png");
            this.imageListGame.Images.SetKeyName(80, "main_bottle.png");
            this.imageListGame.Images.SetKeyName(81, "wood_static_one.png");
            this.imageListGame.Images.SetKeyName(82, "wood_static_one_1.png");
            this.imageListGame.Images.SetKeyName(83, "wood_static_one_2.png");
            this.imageListGame.Images.SetKeyName(84, "wood_static_one_3.png");
            this.imageListGame.Images.SetKeyName(85, "wood_static_one_4.png");
            this.imageListGame.Images.SetKeyName(86, "wood_static_one_5.png");
            this.imageListGame.Images.SetKeyName(87, "wood_static_one_6.png");
            this.imageListGame.Images.SetKeyName(88, "wood_static_one_7.png");
            this.imageListGame.Images.SetKeyName(89, "wood_more_two_static.png");
            this.imageListGame.Images.SetKeyName(90, "wood_more_two_2.png");
            this.imageListGame.Images.SetKeyName(91, "wood_more_two_3.png");
            this.imageListGame.Images.SetKeyName(92, "wood_more_two_4.png");
            this.imageListGame.Images.SetKeyName(93, "wood_moar.png");
            this.imageListGame.Images.SetKeyName(94, "main_grass_2.png");
            this.imageListGame.Images.SetKeyName(95, "main_stone.png");
            this.imageListGame.Images.SetKeyName(96, "arrow_control_up_1.png");
            this.imageListGame.Images.SetKeyName(97, "arrow_control_up_2.png");
            this.imageListGame.Images.SetKeyName(98, "arrow_control_up_3.png");
            this.imageListGame.Images.SetKeyName(99, "arrow_control_up_4.png");
            this.imageListGame.Images.SetKeyName(100, "arrow_control_up_5.png");
            this.imageListGame.Images.SetKeyName(101, "arrow_control_up_6.png");
            this.imageListGame.Images.SetKeyName(102, "arrow_control_down_1.png");
            this.imageListGame.Images.SetKeyName(103, "arrow_control_down_2.png");
            this.imageListGame.Images.SetKeyName(104, "arrow_control_down_3.png");
            this.imageListGame.Images.SetKeyName(105, "arrow_control_down_4.png");
            this.imageListGame.Images.SetKeyName(106, "arrow_control_down_5.png");
            this.imageListGame.Images.SetKeyName(107, "arrow_control_down_6.png");
            this.imageListGame.Images.SetKeyName(108, "arrow_control_left_1.png");
            this.imageListGame.Images.SetKeyName(109, "arrow_control_left_2.png");
            this.imageListGame.Images.SetKeyName(110, "arrow_control_left_3.png");
            this.imageListGame.Images.SetKeyName(111, "arrow_control_left_4.png");
            this.imageListGame.Images.SetKeyName(112, "arrow_control_left_5.png");
            this.imageListGame.Images.SetKeyName(113, "arrow_control_left_6.png");
            this.imageListGame.Images.SetKeyName(114, "arrow_control_right_1.png");
            this.imageListGame.Images.SetKeyName(115, "arrow_control_right_2.png");
            this.imageListGame.Images.SetKeyName(116, "arrow_control_right_3.png");
            this.imageListGame.Images.SetKeyName(117, "arrow_control_right_4.png");
            this.imageListGame.Images.SetKeyName(118, "arrow_control_right_5.png");
            this.imageListGame.Images.SetKeyName(119, "arrow_control_right_6.png");
            this.imageListGame.Images.SetKeyName(120, "hero_down_stand_small_wood.png");
            this.imageListGame.Images.SetKeyName(121, "hero_up_stand_small_wood.png");
            this.imageListGame.Images.SetKeyName(122, "hero_left_stand_small_wood.png");
            this.imageListGame.Images.SetKeyName(123, "hero_right_stand_small_wood.png");
            this.imageListGame.Images.SetKeyName(124, "hero_down_stand_wood.png");
            this.imageListGame.Images.SetKeyName(125, "hero_up_stand_wood.png");
            this.imageListGame.Images.SetKeyName(126, "hero_left_stand_wood.png");
            this.imageListGame.Images.SetKeyName(127, "hero_right_stand_wood.png");
            this.imageListGame.Images.SetKeyName(128, "animate_empty_bottle_1.png");
            this.imageListGame.Images.SetKeyName(129, "animate_empty_bottle_2.png");
            this.imageListGame.Images.SetKeyName(130, "animate_empty_bottle_3.png");
            this.imageListGame.Images.SetKeyName(131, "animate_empty_bottle_4.png");
            this.imageListGame.Images.SetKeyName(132, "animate_empty_bottle_5.png");
            this.imageListGame.Images.SetKeyName(133, "animate_empty_bottle_6.png");
            this.imageListGame.Images.SetKeyName(134, "animate_empty_bottle_7.png");
            this.imageListGame.Images.SetKeyName(135, "animate_empty_bottle_8.png");
            this.imageListGame.Images.SetKeyName(136, "animate_empty_bottle_9.png");
            this.imageListGame.Images.SetKeyName(137, "animate_empty_bottle_10.png");
            this.imageListGame.Images.SetKeyName(138, "hero_down_stand_shovel.png");
            this.imageListGame.Images.SetKeyName(139, "hero_up_stand_shovel.png");
            this.imageListGame.Images.SetKeyName(140, "hero_left_stand_shovel.png");
            this.imageListGame.Images.SetKeyName(141, "hero_right_stand_shovel.png");
            this.imageListGame.Images.SetKeyName(142, "stone_for_attack.png");
            this.imageListGame.Images.SetKeyName(143, "house_2.png");
            this.imageListGame.Images.SetKeyName(144, "house_1.png");
            this.imageListGame.Images.SetKeyName(145, "enemy_standing_down.png");
            this.imageListGame.Images.SetKeyName(146, "enemy_standing_up.png");
            this.imageListGame.Images.SetKeyName(147, "enemy_standing_left.png");
            this.imageListGame.Images.SetKeyName(148, "enemy_standing_right.png");
            this.imageListGame.Images.SetKeyName(149, "hero_bow_standing_down.png");
            this.imageListGame.Images.SetKeyName(150, "hero_bow_standing_up.png");
            this.imageListGame.Images.SetKeyName(151, "hero_bow_standing_left.png");
            this.imageListGame.Images.SetKeyName(152, "hero_bow_standing_right.png");
            this.imageListGame.Images.SetKeyName(153, "arrow_for_attack_down.png");
            this.imageListGame.Images.SetKeyName(154, "arrow_for_attack_up.png");
            this.imageListGame.Images.SetKeyName(155, "arrow_for_attack_left.png");
            this.imageListGame.Images.SetKeyName(156, "arrow_for_attack_right.png");
            this.imageListGame.Images.SetKeyName(157, "small_meat.png");
            this.imageListGame.Images.SetKeyName(158, "large_meat.png");
            this.imageListGame.Images.SetKeyName(159, "corn.png");
            this.imageListGame.Images.SetKeyName(160, "pepper.png");
            this.imageListGame.Images.SetKeyName(161, "tomatoes.png");
            this.imageListGame.Images.SetKeyName(162, "raw_meat.png");
            this.imageListGame.Images.SetKeyName(163, "shovel_tool_map.png");
            this.imageListGame.Images.SetKeyName(164, "heart_1.png");
            this.imageListGame.Images.SetKeyName(165, "coin_1.png");
            this.imageListGame.Images.SetKeyName(166, "damaged_grass_attack_enemy_new.png");
            this.imageListGame.Images.SetKeyName(167, "hero_shield_down.png");
            this.imageListGame.Images.SetKeyName(168, "hero_shield_up.png");
            this.imageListGame.Images.SetKeyName(169, "hero_shield_left.png");
            this.imageListGame.Images.SetKeyName(170, "hero_shield_right.png");
            this.imageListGame.Images.SetKeyName(171, "stump_tree_watering_1.png");
            this.imageListGame.Images.SetKeyName(172, "stump_tree_watering_2.png");
            this.imageListGame.Images.SetKeyName(173, "stump_tree_watering_3.png");
            // 
            // imageListSymbols
            // 
            this.imageListSymbols.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageListSymbols.ImageStream")));
            this.imageListSymbols.TransparentColor = System.Drawing.Color.Transparent;
            this.imageListSymbols.Images.SetKeyName(0, "symbol_zero.png");
            this.imageListSymbols.Images.SetKeyName(1, "symbol_1.png");
            this.imageListSymbols.Images.SetKeyName(2, "symbol_2.png");
            this.imageListSymbols.Images.SetKeyName(3, "symbol_3.png");
            this.imageListSymbols.Images.SetKeyName(4, "symbol_4.png");
            this.imageListSymbols.Images.SetKeyName(5, "symbol_5.png");
            this.imageListSymbols.Images.SetKeyName(6, "symbol_6.png");
            this.imageListSymbols.Images.SetKeyName(7, "symbol_7.png");
            this.imageListSymbols.Images.SetKeyName(8, "symbol_8.png");
            this.imageListSymbols.Images.SetKeyName(9, "symbol_9.png");
            this.imageListSymbols.Images.SetKeyName(10, "Upper_A.png");
            this.imageListSymbols.Images.SetKeyName(11, "Upper_B.png");
            this.imageListSymbols.Images.SetKeyName(12, "Upper_C.png");
            this.imageListSymbols.Images.SetKeyName(13, "Upper_D.png");
            this.imageListSymbols.Images.SetKeyName(14, "Upper_E.png");
            this.imageListSymbols.Images.SetKeyName(15, "Upper_F.png");
            this.imageListSymbols.Images.SetKeyName(16, "Upper_G.png");
            this.imageListSymbols.Images.SetKeyName(17, "Upper_H.png");
            this.imageListSymbols.Images.SetKeyName(18, "Upper_I(i).png");
            this.imageListSymbols.Images.SetKeyName(19, "Upper_J.png");
            this.imageListSymbols.Images.SetKeyName(20, "Upper_K.png");
            this.imageListSymbols.Images.SetKeyName(21, "Upper_L.png");
            this.imageListSymbols.Images.SetKeyName(22, "Upper_M.png");
            this.imageListSymbols.Images.SetKeyName(23, "Upper_N.png");
            this.imageListSymbols.Images.SetKeyName(24, "Upper_O.png");
            this.imageListSymbols.Images.SetKeyName(25, "Upper_P.png");
            this.imageListSymbols.Images.SetKeyName(26, "Upper_Q.png");
            this.imageListSymbols.Images.SetKeyName(27, "Upper_R.png");
            this.imageListSymbols.Images.SetKeyName(28, "Upper_S.png");
            this.imageListSymbols.Images.SetKeyName(29, "Upper_T.png");
            this.imageListSymbols.Images.SetKeyName(30, "Upper_U.png");
            this.imageListSymbols.Images.SetKeyName(31, "Upper_V.png");
            this.imageListSymbols.Images.SetKeyName(32, "Upper_W.png");
            this.imageListSymbols.Images.SetKeyName(33, "Upper_X.png");
            this.imageListSymbols.Images.SetKeyName(34, "Upper_Y.png");
            this.imageListSymbols.Images.SetKeyName(35, "Upper_Z.png");
            this.imageListSymbols.Images.SetKeyName(36, "Lower_a.png");
            this.imageListSymbols.Images.SetKeyName(37, "Lower_b.png");
            this.imageListSymbols.Images.SetKeyName(38, "Lower_c.png");
            this.imageListSymbols.Images.SetKeyName(39, "Lower_d.png");
            this.imageListSymbols.Images.SetKeyName(40, "Lower_e.png");
            this.imageListSymbols.Images.SetKeyName(41, "Lower_f.png");
            this.imageListSymbols.Images.SetKeyName(42, "Lower_g.png");
            this.imageListSymbols.Images.SetKeyName(43, "Lower_h.png");
            this.imageListSymbols.Images.SetKeyName(44, "Lower_i.png");
            this.imageListSymbols.Images.SetKeyName(45, "Lower_j.png");
            this.imageListSymbols.Images.SetKeyName(46, "Lower_k.png");
            this.imageListSymbols.Images.SetKeyName(47, "Lower_l(L).png");
            this.imageListSymbols.Images.SetKeyName(48, "Lower_m.png");
            this.imageListSymbols.Images.SetKeyName(49, "Lower_n.png");
            this.imageListSymbols.Images.SetKeyName(50, "Lower_o.png");
            this.imageListSymbols.Images.SetKeyName(51, "Lower_p.png");
            this.imageListSymbols.Images.SetKeyName(52, "Lower_q.png");
            this.imageListSymbols.Images.SetKeyName(53, "Lower_r.png");
            this.imageListSymbols.Images.SetKeyName(54, "Lower_s.png");
            this.imageListSymbols.Images.SetKeyName(55, "Lower_t.png");
            this.imageListSymbols.Images.SetKeyName(56, "Lower_u.png");
            this.imageListSymbols.Images.SetKeyName(57, "Lower_v.png");
            this.imageListSymbols.Images.SetKeyName(58, "Lower_w.png");
            this.imageListSymbols.Images.SetKeyName(59, "Lower_x.png");
            this.imageListSymbols.Images.SetKeyName(60, "Lower_y.png");
            this.imageListSymbols.Images.SetKeyName(61, "Lower_z.png");
            this.imageListSymbols.Images.SetKeyName(62, "symbol_!.png");
            this.imageListSymbols.Images.SetKeyName(63, "symbol_colon.png");
            this.imageListSymbols.Images.SetKeyName(64, "symbol_continue.png");
            this.imageListSymbols.Images.SetKeyName(65, "symbol_hyphen.png");
            this.imageListSymbols.Images.SetKeyName(66, "symbol_inverted_commas.png");
            this.imageListSymbols.Images.SetKeyName(67, "symbol_point.png");
            this.imageListSymbols.Images.SetKeyName(68, "symbol_question.png");
            this.imageListSymbols.Images.SetKeyName(69, "white_space.png");
            this.imageListSymbols.Images.SetKeyName(70, "symbol_zero_1.png");
            this.imageListSymbols.Images.SetKeyName(71, "symbol_one.png");
            this.imageListSymbols.Images.SetKeyName(72, "symbol_two.png");
            this.imageListSymbols.Images.SetKeyName(73, "symbol_three.png");
            this.imageListSymbols.Images.SetKeyName(74, "symbol_four.png");
            this.imageListSymbols.Images.SetKeyName(75, "symbol_five.png");
            this.imageListSymbols.Images.SetKeyName(76, "symbol_six.png");
            this.imageListSymbols.Images.SetKeyName(77, "symbol_seven.png");
            this.imageListSymbols.Images.SetKeyName(78, "symbol_eight.png");
            this.imageListSymbols.Images.SetKeyName(79, "symbol_nine.png");
            this.imageListSymbols.Images.SetKeyName(80, "Lower_x_counting.png");
            this.imageListSymbols.Images.SetKeyName(81, "Upper_X_counting.png");
            // 
            // menu_timer
            // 
            this.menu_timer.Interval = 80;
            this.menu_timer.Tick += new System.EventHandler(this.menu_timer_Tick);
            // 
            // imgListValues
            // 
            this.imgListValues.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListValues.ImageStream")));
            this.imgListValues.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListValues.Images.SetKeyName(0, "symbol_zero_new.png");
            this.imgListValues.Images.SetKeyName(1, "symbol_1_new.png");
            this.imgListValues.Images.SetKeyName(2, "symbol_2_new.png");
            this.imgListValues.Images.SetKeyName(3, "symbol_3_new.png");
            this.imgListValues.Images.SetKeyName(4, "symbol_4_new.png");
            this.imgListValues.Images.SetKeyName(5, "symbol_5_new.png");
            this.imgListValues.Images.SetKeyName(6, "symbol_6_new.png");
            this.imgListValues.Images.SetKeyName(7, "symbol_7_new.png");
            this.imgListValues.Images.SetKeyName(8, "symbol_8_new.png");
            this.imgListValues.Images.SetKeyName(9, "symbol_9_new.png");
            this.imgListValues.Images.SetKeyName(10, "Lower_x_counting_new.png");
            this.imgListValues.Images.SetKeyName(11, "symbol_slesh_new.png");
            this.imgListValues.Images.SetKeyName(12, "symbol_point_new.png");
            this.imgListValues.Images.SetKeyName(13, "symbol_percent_new.png");
            this.imgListValues.Images.SetKeyName(14, "Upper_F_new.png");
            this.imgListValues.Images.SetKeyName(15, "Upper_E_new.png");
            this.imgListValues.Images.SetKeyName(16, "Upper_X_new.png");
            this.imgListValues.Images.SetKeyName(17, "Upper_P_new.png");
            this.imgListValues.Images.SetKeyName(18, "Upper_L_new.png");
            this.imgListValues.Images.SetKeyName(19, "Upper_V_new.png");
            // 
            // imgUI
            // 
            this.imgUI.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgUI.ImageStream")));
            this.imgUI.TransparentColor = System.Drawing.Color.Transparent;
            this.imgUI.Images.SetKeyName(0, "zero_hearts.png");
            this.imgUI.Images.SetKeyName(1, "one_heart.png");
            this.imgUI.Images.SetKeyName(2, "two_hearts.png");
            this.imgUI.Images.SetKeyName(3, "three_hearts.png");
            this.imgUI.Images.SetKeyName(4, "0_food_points.png");
            this.imgUI.Images.SetKeyName(5, "1_food_points.png");
            this.imgUI.Images.SetKeyName(6, "2_food_points.png");
            this.imgUI.Images.SetKeyName(7, "3_food_points.png");
            this.imgUI.Images.SetKeyName(8, "4_food_points.png");
            this.imgUI.Images.SetKeyName(9, "5_food_points.png");
            this.imgUI.Images.SetKeyName(10, "6_food_points.png");
            this.imgUI.Images.SetKeyName(11, "7_food_points.png");
            this.imgUI.Images.SetKeyName(12, "8_food_points.png");
            this.imgUI.Images.SetKeyName(13, "9_food_points.png");
            this.imgUI.Images.SetKeyName(14, "10_food_points.png");
            this.imgUI.Images.SetKeyName(15, "11_food_points.png");
            this.imgUI.Images.SetKeyName(16, "12_food_points.png");
            this.imgUI.Images.SetKeyName(17, "13_food_points.png");
            this.imgUI.Images.SetKeyName(18, "14_food_points.png");
            this.imgUI.Images.SetKeyName(19, "15_food_points.png");
            this.imgUI.Images.SetKeyName(20, "16_food_points.png");
            this.imgUI.Images.SetKeyName(21, "17_food_points.png");
            this.imgUI.Images.SetKeyName(22, "18_food_points.png");
            this.imgUI.Images.SetKeyName(23, "19_food_points.png");
            this.imgUI.Images.SetKeyName(24, "20_food_points.png");
            this.imgUI.Images.SetKeyName(25, "21_food_points.png");
            this.imgUI.Images.SetKeyName(26, "22_food_points.png");
            this.imgUI.Images.SetKeyName(27, "23_food_points.png");
            this.imgUI.Images.SetKeyName(28, "24_food_points.png");
            this.imgUI.Images.SetKeyName(29, "25_food_points.png");
            this.imgUI.Images.SetKeyName(30, "26_food_points.png");
            this.imgUI.Images.SetKeyName(31, "27_food_points.png");
            this.imgUI.Images.SetKeyName(32, "28_food_points.png");
            this.imgUI.Images.SetKeyName(33, "29_food_points.png");
            this.imgUI.Images.SetKeyName(34, "30_food_points.png");
            this.imgUI.Images.SetKeyName(35, "31_food_points.png");
            this.imgUI.Images.SetKeyName(36, "32_food_points.png");
            this.imgUI.Images.SetKeyName(37, "33_food_points.png");
            this.imgUI.Images.SetKeyName(38, "34_food_points.png");
            this.imgUI.Images.SetKeyName(39, "35_food_points.png");
            this.imgUI.Images.SetKeyName(40, "36_food_points.png");
            this.imgUI.Images.SetKeyName(41, "37_food_points.png");
            this.imgUI.Images.SetKeyName(42, "38_food_points.png");
            this.imgUI.Images.SetKeyName(43, "39_food_points.png");
            this.imgUI.Images.SetKeyName(44, "40_food_points.png");
            this.imgUI.Images.SetKeyName(45, "41_food_points.png");
            this.imgUI.Images.SetKeyName(46, "42_food_points.png");
            this.imgUI.Images.SetKeyName(47, "43_food_points.png");
            this.imgUI.Images.SetKeyName(48, "44_food_points.png");
            this.imgUI.Images.SetKeyName(49, "45_food_points.png");
            this.imgUI.Images.SetKeyName(50, "46_food_points.png");
            this.imgUI.Images.SetKeyName(51, "47_food_points.png");
            this.imgUI.Images.SetKeyName(52, "48_food_points.png");
            this.imgUI.Images.SetKeyName(53, "49_food_points.png");
            this.imgUI.Images.SetKeyName(54, "50_food_points.png");
            this.imgUI.Images.SetKeyName(55, "51_food_points.png");
            this.imgUI.Images.SetKeyName(56, "52_food_points.png");
            this.imgUI.Images.SetKeyName(57, "53_food_points.png");
            this.imgUI.Images.SetKeyName(58, "54_food_points.png");
            this.imgUI.Images.SetKeyName(59, "55_food_points.png");
            this.imgUI.Images.SetKeyName(60, "56_food_points.png");
            this.imgUI.Images.SetKeyName(61, "57_food_points.png");
            this.imgUI.Images.SetKeyName(62, "58_food_points.png");
            this.imgUI.Images.SetKeyName(63, "59_food_points.png");
            this.imgUI.Images.SetKeyName(64, "60_food_points.png");
            this.imgUI.Images.SetKeyName(65, "61_food_points.png");
            this.imgUI.Images.SetKeyName(66, "62_food_points.png");
            this.imgUI.Images.SetKeyName(67, "63_food_points.png");
            this.imgUI.Images.SetKeyName(68, "64_food_points.png");
            this.imgUI.Images.SetKeyName(69, "65_food_points.png");
            this.imgUI.Images.SetKeyName(70, "66_food_points.png");
            this.imgUI.Images.SetKeyName(71, "67_food_points.png");
            this.imgUI.Images.SetKeyName(72, "68_food_points.png");
            this.imgUI.Images.SetKeyName(73, "69_food_points.png");
            this.imgUI.Images.SetKeyName(74, "70_food_points.png");
            this.imgUI.Images.SetKeyName(75, "71_food_points.png");
            this.imgUI.Images.SetKeyName(76, "72_food_points.png");
            this.imgUI.Images.SetKeyName(77, "73_food_points.png");
            this.imgUI.Images.SetKeyName(78, "74_food_points.png");
            this.imgUI.Images.SetKeyName(79, "75_food_points.png");
            this.imgUI.Images.SetKeyName(80, "76_food_points.png");
            this.imgUI.Images.SetKeyName(81, "77_food_points.png");
            this.imgUI.Images.SetKeyName(82, "78_food_points.png");
            this.imgUI.Images.SetKeyName(83, "79_food_points.png");
            this.imgUI.Images.SetKeyName(84, "80_food_points.png");
            this.imgUI.Images.SetKeyName(85, "81_food_points.png");
            this.imgUI.Images.SetKeyName(86, "82_food_points.png");
            this.imgUI.Images.SetKeyName(87, "83_food_points.png");
            this.imgUI.Images.SetKeyName(88, "84_food_points.png");
            this.imgUI.Images.SetKeyName(89, "85_food_points.png");
            this.imgUI.Images.SetKeyName(90, "86_food_points.png");
            this.imgUI.Images.SetKeyName(91, "87_food_points.png");
            this.imgUI.Images.SetKeyName(92, "88_food_points.png");
            this.imgUI.Images.SetKeyName(93, "89_food_points.png");
            this.imgUI.Images.SetKeyName(94, "90_food_points.png");
            this.imgUI.Images.SetKeyName(95, "91_food_points.png");
            this.imgUI.Images.SetKeyName(96, "92_food_points.png");
            this.imgUI.Images.SetKeyName(97, "93_food_points.png");
            this.imgUI.Images.SetKeyName(98, "94_food_points.png");
            this.imgUI.Images.SetKeyName(99, "95_food_points.png");
            this.imgUI.Images.SetKeyName(100, "96_food_points.png");
            this.imgUI.Images.SetKeyName(101, "97_food_points.png");
            this.imgUI.Images.SetKeyName(102, "98_food_points.png");
            this.imgUI.Images.SetKeyName(103, "99_food_points.png");
            this.imgUI.Images.SetKeyName(104, "100_food_points.png");
            // 
            // imgUI_EnergyPoints
            // 
            this.imgUI_EnergyPoints.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgUI_EnergyPoints.ImageStream")));
            this.imgUI_EnergyPoints.TransparentColor = System.Drawing.Color.Transparent;
            this.imgUI_EnergyPoints.Images.SetKeyName(0, "zero_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(1, "1_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(2, "2_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(3, "3_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(4, "4_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(5, "5_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(6, "6_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(7, "7_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(8, "8_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(9, "9_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(10, "10_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(11, "11_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(12, "12_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(13, "13_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(14, "14_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(15, "15_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(16, "16_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(17, "17_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(18, "18_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(19, "19_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(20, "20_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(21, "21_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(22, "22_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(23, "23_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(24, "24_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(25, "25_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(26, "26_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(27, "27_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(28, "28_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(29, "29_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(30, "30_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(31, "31_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(32, "32_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(33, "33_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(34, "34_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(35, "35_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(36, "36_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(37, "37_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(38, "38_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(39, "39_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(40, "40_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(41, "41_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(42, "42_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(43, "43_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(44, "44_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(45, "45_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(46, "46_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(47, "47_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(48, "48_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(49, "49_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(50, "50_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(51, "51_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(52, "52_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(53, "53_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(54, "54_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(55, "55_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(56, "56_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(57, "57_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(58, "58_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(59, "59_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(60, "60_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(61, "61_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(62, "62_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(63, "63_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(64, "64_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(65, "65_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(66, "66_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(67, "67_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(68, "68_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(69, "69_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(70, "70_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(71, "71_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(72, "72_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(73, "73_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(74, "74_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(75, "75_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(76, "76_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(77, "77_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(78, "78_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(79, "79_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(80, "80_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(81, "81_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(82, "82_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(83, "83_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(84, "84_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(85, "85_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(86, "86_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(87, "87_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(88, "88_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(89, "89_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(90, "90_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(91, "91_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(92, "92_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(93, "93_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(94, "94_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(95, "95_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(96, "96_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(97, "97_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(98, "98_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(99, "99_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(100, "100_energy_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(101, "energy_points_locked.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(102, "zero_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(103, "1_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(104, "2_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(105, "3_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(106, "4_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(107, "5_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(108, "6_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(109, "7_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(110, "8_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(111, "9_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(112, "10_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(113, "11_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(114, "12_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(115, "13_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(116, "14_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(117, "15_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(118, "16_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(119, "17_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(120, "18_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(121, "19_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(122, "20_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(123, "21_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(124, "22_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(125, "23_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(126, "24_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(127, "25_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(128, "26_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(129, "27_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(130, "28_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(131, "29_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(132, "30_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(133, "31_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(134, "32_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(135, "33_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(136, "34_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(137, "35_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(138, "36_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(139, "37_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(140, "38_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(141, "39_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(142, "40_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(143, "41_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(144, "42_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(145, "43_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(146, "44_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(147, "45_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(148, "46_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(149, "47_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(150, "48_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(151, "49_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(152, "50_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(153, "51_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(154, "52_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(155, "53_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(156, "54_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(157, "55_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(158, "56_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(159, "57_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(160, "58_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(161, "59_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(162, "60_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(163, "61_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(164, "62_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(165, "63_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(166, "64_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(167, "65_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(168, "66_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(169, "67_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(170, "68_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(171, "69_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(172, "70_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(173, "71_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(174, "72_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(175, "73_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(176, "74_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(177, "75_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(178, "76_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(179, "77_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(180, "78_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(181, "79_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(182, "80_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(183, "81_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(184, "82_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(185, "83_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(186, "84_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(187, "85_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(188, "86_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(189, "87_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(190, "88_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(191, "89_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(192, "90_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(193, "91_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(194, "92_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(195, "93_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(196, "94_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(197, "95_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(198, "96_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(199, "97_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(200, "98_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(201, "99_lvl_points.png");
            this.imgUI_EnergyPoints.Images.SetKeyName(202, "100_lvl_points.png");
            // 
            // imgHeroValues
            // 
            this.imgHeroValues.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgHeroValues.ImageStream")));
            this.imgHeroValues.TransparentColor = System.Drawing.Color.Transparent;
            this.imgHeroValues.Images.SetKeyName(0, "symbol_zero_food.png");
            this.imgHeroValues.Images.SetKeyName(1, "symbol_1_food.png");
            this.imgHeroValues.Images.SetKeyName(2, "symbol_2_food.png");
            this.imgHeroValues.Images.SetKeyName(3, "symbol_3_food.png");
            this.imgHeroValues.Images.SetKeyName(4, "symbol_4_food.png");
            this.imgHeroValues.Images.SetKeyName(5, "symbol_5_food.png");
            this.imgHeroValues.Images.SetKeyName(6, "symbol_6_food.png");
            this.imgHeroValues.Images.SetKeyName(7, "symbol_7_food.png");
            this.imgHeroValues.Images.SetKeyName(8, "symbol_8_food.png");
            this.imgHeroValues.Images.SetKeyName(9, "symbol_9_food.png");
            this.imgHeroValues.Images.SetKeyName(10, "symbol_zero_energy.png");
            this.imgHeroValues.Images.SetKeyName(11, "symbol_1_energy.png");
            this.imgHeroValues.Images.SetKeyName(12, "symbol_2_energy.png");
            this.imgHeroValues.Images.SetKeyName(13, "symbol_3_energy.png");
            this.imgHeroValues.Images.SetKeyName(14, "symbol_4_energy.png");
            this.imgHeroValues.Images.SetKeyName(15, "symbol_5_energy.png");
            this.imgHeroValues.Images.SetKeyName(16, "symbol_6_energy.png");
            this.imgHeroValues.Images.SetKeyName(17, "symbol_7_energy.png");
            this.imgHeroValues.Images.SetKeyName(18, "symbol_8_energy.png");
            this.imgHeroValues.Images.SetKeyName(19, "symbol_9_energy.png");
            // 
            // imgListInventory
            // 
            this.imgListInventory.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListInventory.ImageStream")));
            this.imgListInventory.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListInventory.Images.SetKeyName(0, "empty_inventory_cell.png");
            this.imgListInventory.Images.SetKeyName(1, "inventory_sword_item.png");
            this.imgListInventory.Images.SetKeyName(2, "inventory_bow_item.png");
            this.imgListInventory.Images.SetKeyName(3, "inventory_wood_item.png");
            this.imgListInventory.Images.SetKeyName(4, "inventory_stone_item.png");
            this.imgListInventory.Images.SetKeyName(5, "inventory_bottle_item.png");
            this.imgListInventory.Images.SetKeyName(6, "inventory_bottle_water_item.png");
            this.imgListInventory.Images.SetKeyName(7, "inventory_sword_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(8, "inventory_sword_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(9, "inventory_sword_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(10, "inventory_sword_item_focus_4.png");
            this.imgListInventory.Images.SetKeyName(11, "inventory_bow_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(12, "inventory_bow_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(13, "inventory_bow_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(14, "inventory_bow_item_focus_4.png");
            this.imgListInventory.Images.SetKeyName(15, "inventory_wood_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(16, "inventory_wood_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(17, "inventory_wood_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(18, "inventory_wood_item_focus_4.png");
            this.imgListInventory.Images.SetKeyName(19, "inventory_stone_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(20, "inventory_stone_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(21, "inventory_stone_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(22, "inventory_stone_item_focus_4.png");
            this.imgListInventory.Images.SetKeyName(23, "inventory_bottle_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(24, "inventory_bottle_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(25, "inventory_bottle_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(26, "inventory_bottle_item_focus_4.png");
            this.imgListInventory.Images.SetKeyName(27, "inventory_bottle_water_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(28, "inventory_bottle_water_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(29, "inventory_bottle_water_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(30, "inventory_bottle_water_item_focus_4.png");
            this.imgListInventory.Images.SetKeyName(31, "inventory_shovel_item.png");
            this.imgListInventory.Images.SetKeyName(32, "inventory_shovel_item_focus_1.png");
            this.imgListInventory.Images.SetKeyName(33, "inventory_shovel_item_focus_2.png");
            this.imgListInventory.Images.SetKeyName(34, "inventory_shovel_item_focus_3.png");
            this.imgListInventory.Images.SetKeyName(35, "inventory_shovel_item_focus_4.png");
            // 
            // imgListHeroWater
            // 
            this.imgListHeroWater.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListHeroWater.ImageStream")));
            this.imgListHeroWater.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListHeroWater.Images.SetKeyName(0, "hero_get_water_down_1.png");
            this.imgListHeroWater.Images.SetKeyName(1, "hero_get_water_down_2.png");
            this.imgListHeroWater.Images.SetKeyName(2, "hero_get_water_down_3.png");
            this.imgListHeroWater.Images.SetKeyName(3, "hero_get_water_down_4.png");
            this.imgListHeroWater.Images.SetKeyName(4, "hero_get_water_down_5.png");
            this.imgListHeroWater.Images.SetKeyName(5, "hero_get_water_down_6.png");
            this.imgListHeroWater.Images.SetKeyName(6, "hero_get_water_up_1.png");
            this.imgListHeroWater.Images.SetKeyName(7, "hero_get_water_up_2.png");
            this.imgListHeroWater.Images.SetKeyName(8, "hero_get_water_up_3.png");
            this.imgListHeroWater.Images.SetKeyName(9, "hero_get_water_up_4.png");
            this.imgListHeroWater.Images.SetKeyName(10, "hero_get_water_up_5.png");
            this.imgListHeroWater.Images.SetKeyName(11, "hero_get_water_up_6.png");
            this.imgListHeroWater.Images.SetKeyName(12, "hero_get_water_left_1.png");
            this.imgListHeroWater.Images.SetKeyName(13, "hero_get_water_left_2.png");
            this.imgListHeroWater.Images.SetKeyName(14, "hero_get_water_left_3.png");
            this.imgListHeroWater.Images.SetKeyName(15, "hero_get_water_left_4.png");
            this.imgListHeroWater.Images.SetKeyName(16, "hero_get_water_left_5.png");
            this.imgListHeroWater.Images.SetKeyName(17, "hero_get_water_left_6.png");
            this.imgListHeroWater.Images.SetKeyName(18, "hero_get_water_right_1.png");
            this.imgListHeroWater.Images.SetKeyName(19, "hero_get_water_right_2.png");
            this.imgListHeroWater.Images.SetKeyName(20, "hero_get_water_right_3.png");
            this.imgListHeroWater.Images.SetKeyName(21, "hero_get_water_right_4.png");
            this.imgListHeroWater.Images.SetKeyName(22, "hero_get_water_right_5.png");
            this.imgListHeroWater.Images.SetKeyName(23, "hero_get_water_right_6.png");
            // 
            // imgListInterface
            // 
            this.imgListInterface.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListInterface.ImageStream")));
            this.imgListInterface.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListInterface.Images.SetKeyName(0, "interface_sword_tool.png");
            this.imgListInterface.Images.SetKeyName(1, "interface_bow_tool.png");
            this.imgListInterface.Images.SetKeyName(2, "interface_shovel_tool.png");
            this.imgListInterface.Images.SetKeyName(3, "interface_sword_tool_focus_1.png");
            this.imgListInterface.Images.SetKeyName(4, "interface_sword_tool_focus_2.png");
            this.imgListInterface.Images.SetKeyName(5, "interface_sword_tool_focus_3.png");
            this.imgListInterface.Images.SetKeyName(6, "interface_sword_tool_focus_4.png");
            this.imgListInterface.Images.SetKeyName(7, "interface_bow_tool_focus_1.png");
            this.imgListInterface.Images.SetKeyName(8, "interface_bow_tool_focus_2.png");
            this.imgListInterface.Images.SetKeyName(9, "interface_bow_tool_focus_3.png");
            this.imgListInterface.Images.SetKeyName(10, "interface_bow_tool_focus_4.png");
            this.imgListInterface.Images.SetKeyName(11, "interface_shovel_tool_focus_1.png");
            this.imgListInterface.Images.SetKeyName(12, "interface_shovel_tool_focus_2.png");
            this.imgListInterface.Images.SetKeyName(13, "interface_shovel_tool_focus_3.png");
            this.imgListInterface.Images.SetKeyName(14, "interface_shovel_tool_focus_4.png");
            this.imgListInterface.Images.SetKeyName(15, "interface_arrows_tool.png");
            // 
            // imgListStone
            // 
            this.imgListStone.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListStone.ImageStream")));
            this.imgListStone.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListStone.Images.SetKeyName(0, "stone_health_10.png");
            this.imgListStone.Images.SetKeyName(1, "stone_health_20.png");
            this.imgListStone.Images.SetKeyName(2, "stone_health_30.png");
            this.imgListStone.Images.SetKeyName(3, "stone_health_40.png");
            this.imgListStone.Images.SetKeyName(4, "stone_health_55.png");
            this.imgListStone.Images.SetKeyName(5, "stone_health_70.png");
            this.imgListStone.Images.SetKeyName(6, "stone_health_85.png");
            this.imgListStone.Images.SetKeyName(7, "stone_health_100.png");
            this.imgListStone.Images.SetKeyName(8, "animate_stone_1.png");
            this.imgListStone.Images.SetKeyName(9, "animate_stone_2.png");
            this.imgListStone.Images.SetKeyName(10, "animate_stone_3.png");
            this.imgListStone.Images.SetKeyName(11, "animate_stone_4.png");
            this.imgListStone.Images.SetKeyName(12, "animate_stone_5.png");
            this.imgListStone.Images.SetKeyName(13, "animate_stone_6.png");
            this.imgListStone.Images.SetKeyName(14, "animate_stone_7.png");
            this.imgListStone.Images.SetKeyName(15, "animate_stone_8.png");
            this.imgListStone.Images.SetKeyName(16, "animate_stone_9.png");
            this.imgListStone.Images.SetKeyName(17, "animate_stone_10.png");
            this.imgListStone.Images.SetKeyName(18, "animate_stone_11.png");
            this.imgListStone.Images.SetKeyName(19, "stone_destroying_1.png");
            this.imgListStone.Images.SetKeyName(20, "stone_destroying_2.png");
            this.imgListStone.Images.SetKeyName(21, "stone_destroying_3.png");
            this.imgListStone.Images.SetKeyName(22, "stone_destroying_4.png");
            this.imgListStone.Images.SetKeyName(23, "stone_for_attack.png");
            // 
            // imgForBuilding
            // 
            this.imgForBuilding.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgForBuilding.ImageStream")));
            this.imgForBuilding.TransparentColor = System.Drawing.Color.Transparent;
            this.imgForBuilding.Images.SetKeyName(0, "main_river.png");
            this.imgForBuilding.Images.SetKeyName(1, "river_center_bottom.png");
            this.imgForBuilding.Images.SetKeyName(2, "river_center_top.png");
            this.imgForBuilding.Images.SetKeyName(3, "river_left_bottom.png");
            this.imgForBuilding.Images.SetKeyName(4, "river_left_bottom_edge.png");
            this.imgForBuilding.Images.SetKeyName(5, "river_left_middle.png");
            this.imgForBuilding.Images.SetKeyName(6, "river_left_top.png");
            this.imgForBuilding.Images.SetKeyName(7, "river_left_top_edge.png");
            this.imgForBuilding.Images.SetKeyName(8, "river_right_bottom.png");
            this.imgForBuilding.Images.SetKeyName(9, "river_right_bottom_edge.png");
            this.imgForBuilding.Images.SetKeyName(10, "river_right_middle.png");
            this.imgForBuilding.Images.SetKeyName(11, "river_right_top.png");
            this.imgForBuilding.Images.SetKeyName(12, "river_right_top_edge.png");
            this.imgForBuilding.Images.SetKeyName(13, "main_grass.png");
            this.imgForBuilding.Images.SetKeyName(14, "main_stone_building.png");
            this.imgForBuilding.Images.SetKeyName(15, "main_tree_building.png");
            this.imgForBuilding.Images.SetKeyName(16, "stump_tree.png");
            // 
            // imgListRoom
            // 
            this.imgListRoom.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListRoom.ImageStream")));
            this.imgListRoom.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListRoom.Images.SetKeyName(0, "main_room_empty.png");
            this.imgListRoom.Images.SetKeyName(1, "main_room_floor.png");
            this.imgListRoom.Images.SetKeyName(2, "chair_savegame.png");
            this.imgListRoom.Images.SetKeyName(3, "hero_standing_room_down.png");
            this.imgListRoom.Images.SetKeyName(4, "hero_standing_room_up.png");
            this.imgListRoom.Images.SetKeyName(5, "hero_standing_room_left.png");
            this.imgListRoom.Images.SetKeyName(6, "hero_standing_room_right.png");
            this.imgListRoom.Images.SetKeyName(7, "hero_running_room_down_1.png");
            this.imgListRoom.Images.SetKeyName(8, "hero_running_room_down_2.png");
            this.imgListRoom.Images.SetKeyName(9, "hero_running_room_up_1.png");
            this.imgListRoom.Images.SetKeyName(10, "hero_running_room_up_2.png");
            this.imgListRoom.Images.SetKeyName(11, "hero_running_room_left_1.png");
            this.imgListRoom.Images.SetKeyName(12, "hero_running_room_left_2.png");
            this.imgListRoom.Images.SetKeyName(13, "hero_running_room_right_1.png");
            this.imgListRoom.Images.SetKeyName(14, "hero_running_room_right_2.png");
            this.imgListRoom.Images.SetKeyName(15, "chair_savegame_hero_1.png");
            this.imgListRoom.Images.SetKeyName(16, "chair_savegame_hero_2.png");
            // 
            // imgListEnemy
            // 
            this.imgListEnemy.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListEnemy.ImageStream")));
            this.imgListEnemy.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListEnemy.Images.SetKeyName(0, "enemy_running_down_1.png");
            this.imgListEnemy.Images.SetKeyName(1, "enemy_running_down_2.png");
            this.imgListEnemy.Images.SetKeyName(2, "enemy_running_down_3.png");
            this.imgListEnemy.Images.SetKeyName(3, "enemy_running_down_4.png");
            this.imgListEnemy.Images.SetKeyName(4, "enemy_running_up_1.png");
            this.imgListEnemy.Images.SetKeyName(5, "enemy_running_up_2.png");
            this.imgListEnemy.Images.SetKeyName(6, "enemy_running_up_3.png");
            this.imgListEnemy.Images.SetKeyName(7, "enemy_running_up_4.png");
            this.imgListEnemy.Images.SetKeyName(8, "enemy_running_left_1.png");
            this.imgListEnemy.Images.SetKeyName(9, "enemy_running_left_2.png");
            this.imgListEnemy.Images.SetKeyName(10, "enemy_running_left_3.png");
            this.imgListEnemy.Images.SetKeyName(11, "enemy_running_left_4.png");
            this.imgListEnemy.Images.SetKeyName(12, "enemy_running_right_1.png");
            this.imgListEnemy.Images.SetKeyName(13, "enemy_running_right_2.png");
            this.imgListEnemy.Images.SetKeyName(14, "enemy_running_right_3.png");
            this.imgListEnemy.Images.SetKeyName(15, "enemy_running_right_4.png");
            this.imgListEnemy.Images.SetKeyName(16, "enemy_in_water_2.png");
            this.imgListEnemy.Images.SetKeyName(17, "enemy_in_water_3.png");
            this.imgListEnemy.Images.SetKeyName(18, "enemy_in_water_4.png");
            this.imgListEnemy.Images.SetKeyName(19, "enemy_in_water_5.png");
            this.imgListEnemy.Images.SetKeyName(20, "enemy_in_water_6.png");
            this.imgListEnemy.Images.SetKeyName(21, "enemy_incoming_1.png");
            this.imgListEnemy.Images.SetKeyName(22, "enemy_incoming_2.png");
            this.imgListEnemy.Images.SetKeyName(23, "enemy_incoming_3.png");
            this.imgListEnemy.Images.SetKeyName(24, "enemy_incoming_4.png");
            this.imgListEnemy.Images.SetKeyName(25, "enemy_incoming_5.png");
            this.imgListEnemy.Images.SetKeyName(26, "enemy_incoming_6.png");
            this.imgListEnemy.Images.SetKeyName(27, "enemy_incoming_7.png");
            this.imgListEnemy.Images.SetKeyName(28, "enemy_incoming_8.png");
            this.imgListEnemy.Images.SetKeyName(29, "enemy_incoming_9.png");
            this.imgListEnemy.Images.SetKeyName(30, "enemy_incoming_10.png");
            this.imgListEnemy.Images.SetKeyName(31, "enemy_incoming_11.png");
            this.imgListEnemy.Images.SetKeyName(32, "enemy_incoming_12.png");
            this.imgListEnemy.Images.SetKeyName(33, "enemy_incoming_13.png");
            this.imgListEnemy.Images.SetKeyName(34, "enemy_incoming_14.png");
            this.imgListEnemy.Images.SetKeyName(35, "enemy_incoming_15.png");
            this.imgListEnemy.Images.SetKeyName(36, "enemy_dying_by_sword_down_1.png");
            this.imgListEnemy.Images.SetKeyName(37, "enemy_dying_by_sword_down_2.png");
            this.imgListEnemy.Images.SetKeyName(38, "enemy_dying_by_sword_down_3.png");
            this.imgListEnemy.Images.SetKeyName(39, "enemy_dying_by_sword_down_4.png");
            this.imgListEnemy.Images.SetKeyName(40, "enemy_dying_by_sword_down_5.png");
            this.imgListEnemy.Images.SetKeyName(41, "enemy_dying_by_arrow_1.png");
            this.imgListEnemy.Images.SetKeyName(42, "enemy_dying_by_arrow_2.png");
            this.imgListEnemy.Images.SetKeyName(43, "enemy_dying_by_arrow_3.png");
            this.imgListEnemy.Images.SetKeyName(44, "enemy_dying_by_arrow_4.png");
            this.imgListEnemy.Images.SetKeyName(45, "enemy_dying_by_arrow_5.png");
            this.imgListEnemy.Images.SetKeyName(46, "enemy_dying_by_arrow_6.png");
            this.imgListEnemy.Images.SetKeyName(47, "enemy_dying_by_arrow_7.png");
            this.imgListEnemy.Images.SetKeyName(48, "enemy_dying_by_arrow_8.png");
            this.imgListEnemy.Images.SetKeyName(49, "enemy_dying_by_arrow_9.png");
            this.imgListEnemy.Images.SetKeyName(50, "enemy_damaged_left_1.png");
            this.imgListEnemy.Images.SetKeyName(51, "enemy_damaged_left_2.png");
            this.imgListEnemy.Images.SetKeyName(52, "enemy_damaged_left_3.png");
            this.imgListEnemy.Images.SetKeyName(53, "enemy_damaged_left_4.png");
            this.imgListEnemy.Images.SetKeyName(54, "enemy_damaged_left_5.png");
            this.imgListEnemy.Images.SetKeyName(55, "enemy_damaged_left_6.png");
            this.imgListEnemy.Images.SetKeyName(56, "enemy_damaged_right_1.png");
            this.imgListEnemy.Images.SetKeyName(57, "enemy_damaged_right_2.png");
            this.imgListEnemy.Images.SetKeyName(58, "enemy_damaged_right_3.png");
            this.imgListEnemy.Images.SetKeyName(59, "enemy_damaged_right_4.png");
            this.imgListEnemy.Images.SetKeyName(60, "enemy_damaged_right_5.png");
            this.imgListEnemy.Images.SetKeyName(61, "enemy_damaged_right_6.png");
            // 
            // imgListBow
            // 
            this.imgListBow.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListBow.ImageStream")));
            this.imgListBow.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListBow.Images.SetKeyName(0, "hero_bow_attack_down_1.png");
            this.imgListBow.Images.SetKeyName(1, "hero_bow_attack_down_2.png");
            this.imgListBow.Images.SetKeyName(2, "hero_bow_attack_down_3.png");
            this.imgListBow.Images.SetKeyName(3, "hero_bow_attack_left_1.png");
            this.imgListBow.Images.SetKeyName(4, "hero_bow_attack_left_2.png");
            this.imgListBow.Images.SetKeyName(5, "hero_bow_attack_left_3.png");
            this.imgListBow.Images.SetKeyName(6, "hero_bow_attack_right_1.png");
            this.imgListBow.Images.SetKeyName(7, "hero_bow_attack_right_2.png");
            this.imgListBow.Images.SetKeyName(8, "hero_bow_attack_right_3.png");
            this.imgListBow.Images.SetKeyName(9, "stone_destroying_1.png");
            this.imgListBow.Images.SetKeyName(10, "stone_destroying_2.png");
            this.imgListBow.Images.SetKeyName(11, "stone_destroying_3.png");
            this.imgListBow.Images.SetKeyName(12, "stone_destroying_4.png");
            // 
            // imgListItems
            // 
            this.imgListItems.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListItems.ImageStream")));
            this.imgListItems.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListItems.Images.SetKeyName(0, "animate_small_meat_1.png");
            this.imgListItems.Images.SetKeyName(1, "animate_small_meat_2.png");
            this.imgListItems.Images.SetKeyName(2, "animate_small_meat_3.png");
            this.imgListItems.Images.SetKeyName(3, "animate_small_meat_4.png");
            this.imgListItems.Images.SetKeyName(4, "animate_small_meat_5.png");
            this.imgListItems.Images.SetKeyName(5, "animate_small_meat_6.png");
            this.imgListItems.Images.SetKeyName(6, "animate_small_meat_7.png");
            this.imgListItems.Images.SetKeyName(7, "animate_small_meat_8.png");
            this.imgListItems.Images.SetKeyName(8, "animate_large_meat_1.png");
            this.imgListItems.Images.SetKeyName(9, "animate_large_meat_2.png");
            this.imgListItems.Images.SetKeyName(10, "animate_large_meat_3.png");
            this.imgListItems.Images.SetKeyName(11, "animate_large_meat_4.png");
            this.imgListItems.Images.SetKeyName(12, "animate_large_meat_5.png");
            this.imgListItems.Images.SetKeyName(13, "animate_large_meat_6.png");
            this.imgListItems.Images.SetKeyName(14, "animate_large_meat_7.png");
            this.imgListItems.Images.SetKeyName(15, "animate_large_meat_8.png");
            this.imgListItems.Images.SetKeyName(16, "animate_corn_1.png");
            this.imgListItems.Images.SetKeyName(17, "animate_corn_2.png");
            this.imgListItems.Images.SetKeyName(18, "animate_corn_3.png");
            this.imgListItems.Images.SetKeyName(19, "animate_corn_4.png");
            this.imgListItems.Images.SetKeyName(20, "animate_corn_5.png");
            this.imgListItems.Images.SetKeyName(21, "animate_corn_6.png");
            this.imgListItems.Images.SetKeyName(22, "animate_corn_7.png");
            this.imgListItems.Images.SetKeyName(23, "animate_corn_8.png");
            this.imgListItems.Images.SetKeyName(24, "animate_pepper_1.png");
            this.imgListItems.Images.SetKeyName(25, "animate_pepper_2.png");
            this.imgListItems.Images.SetKeyName(26, "animate_pepper_3.png");
            this.imgListItems.Images.SetKeyName(27, "animate_pepper_4.png");
            this.imgListItems.Images.SetKeyName(28, "animate_pepper_5.png");
            this.imgListItems.Images.SetKeyName(29, "animate_pepper_6.png");
            this.imgListItems.Images.SetKeyName(30, "animate_pepper_7.png");
            this.imgListItems.Images.SetKeyName(31, "animate_pepper_8.png");
            this.imgListItems.Images.SetKeyName(32, "animate_tomatoes_1.png");
            this.imgListItems.Images.SetKeyName(33, "animate_tomatoes_2.png");
            this.imgListItems.Images.SetKeyName(34, "animate_tomatoes_3.png");
            this.imgListItems.Images.SetKeyName(35, "animate_tomatoes_4.png");
            this.imgListItems.Images.SetKeyName(36, "animate_tomatoes_5.png");
            this.imgListItems.Images.SetKeyName(37, "animate_tomatoes_6.png");
            this.imgListItems.Images.SetKeyName(38, "animate_tomatoes_7.png");
            this.imgListItems.Images.SetKeyName(39, "animate_tomatoes_8.png");
            this.imgListItems.Images.SetKeyName(40, "animate_raw_meat_1.png");
            this.imgListItems.Images.SetKeyName(41, "animate_raw_meat_2.png");
            this.imgListItems.Images.SetKeyName(42, "animate_raw_meat_3.png");
            this.imgListItems.Images.SetKeyName(43, "animate_raw_meat_4.png");
            this.imgListItems.Images.SetKeyName(44, "animate_raw_meat_5.png");
            this.imgListItems.Images.SetKeyName(45, "animate_raw_meat_6.png");
            this.imgListItems.Images.SetKeyName(46, "animate_raw_meat_7.png");
            this.imgListItems.Images.SetKeyName(47, "animate_raw_meat_8.png");
            this.imgListItems.Images.SetKeyName(48, "heart_1.png");
            this.imgListItems.Images.SetKeyName(49, "heart_2.png");
            this.imgListItems.Images.SetKeyName(50, "heart_3.png");
            this.imgListItems.Images.SetKeyName(51, "heart_4.png");
            this.imgListItems.Images.SetKeyName(52, "coin_1.png");
            this.imgListItems.Images.SetKeyName(53, "coin_2.png");
            this.imgListItems.Images.SetKeyName(54, "coin_3.png");
            this.imgListItems.Images.SetKeyName(55, "coin_4.png");
            this.imgListItems.Images.SetKeyName(56, "heart_incoming_1.png");
            this.imgListItems.Images.SetKeyName(57, "heart_incoming_2.png");
            this.imgListItems.Images.SetKeyName(58, "heart_incoming_3.png");
            this.imgListItems.Images.SetKeyName(59, "heart_incoming_4.png");
            this.imgListItems.Images.SetKeyName(60, "heart_incoming_5.png");
            this.imgListItems.Images.SetKeyName(61, "heart_incoming_6.png");
            this.imgListItems.Images.SetKeyName(62, "animate_shovel_tool_1.png");
            this.imgListItems.Images.SetKeyName(63, "animate_shovel_tool_2.png");
            this.imgListItems.Images.SetKeyName(64, "animate_shovel_tool_3.png");
            this.imgListItems.Images.SetKeyName(65, "animate_shovel_tool_4.png");
            this.imgListItems.Images.SetKeyName(66, "animate_shovel_tool_5.png");
            this.imgListItems.Images.SetKeyName(67, "animate_shovel_tool_6.png");
            this.imgListItems.Images.SetKeyName(68, "animate_shovel_tool_7.png");
            this.imgListItems.Images.SetKeyName(69, "animate_shovel_tool_8.png");
            // 
            // imgListEnemyAttack
            // 
            this.imgListEnemyAttack.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListEnemyAttack.ImageStream")));
            this.imgListEnemyAttack.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListEnemyAttack.Images.SetKeyName(0, "enemy_attack_hero_down_1.png");
            this.imgListEnemyAttack.Images.SetKeyName(1, "enemy_attack_hero_down_2.png");
            this.imgListEnemyAttack.Images.SetKeyName(2, "enemy_attack_hero_down_3.png");
            this.imgListEnemyAttack.Images.SetKeyName(3, "enemy_attack_hero_down_4.png");
            this.imgListEnemyAttack.Images.SetKeyName(4, "enemy_attack_hero_down_5.png");
            this.imgListEnemyAttack.Images.SetKeyName(5, "enemy_attack_hero_down_6.png");
            this.imgListEnemyAttack.Images.SetKeyName(6, "enemy_attack_hero_up_1.png");
            this.imgListEnemyAttack.Images.SetKeyName(7, "enemy_attack_hero_up_2.png");
            this.imgListEnemyAttack.Images.SetKeyName(8, "enemy_attack_hero_up_3.png");
            this.imgListEnemyAttack.Images.SetKeyName(9, "enemy_attack_hero_up_4.png");
            this.imgListEnemyAttack.Images.SetKeyName(10, "enemy_attack_hero_left_1.png");
            this.imgListEnemyAttack.Images.SetKeyName(11, "enemy_attack_hero_left_2.png");
            this.imgListEnemyAttack.Images.SetKeyName(12, "enemy_attack_hero_left_3.png");
            this.imgListEnemyAttack.Images.SetKeyName(13, "enemy_attack_hero_left_5.png");
            this.imgListEnemyAttack.Images.SetKeyName(14, "enemy_attack_hero_left_6.png");
            this.imgListEnemyAttack.Images.SetKeyName(15, "enemy_attack_hero_left_7.png");
            this.imgListEnemyAttack.Images.SetKeyName(16, "enemy_attack_hero_left_8.png");
            this.imgListEnemyAttack.Images.SetKeyName(17, "enemy_attack_hero_right_1.png");
            this.imgListEnemyAttack.Images.SetKeyName(18, "enemy_attack_hero_right_2.png");
            this.imgListEnemyAttack.Images.SetKeyName(19, "enemy_attack_hero_right_3.png");
            this.imgListEnemyAttack.Images.SetKeyName(20, "enemy_attack_hero_right_4.png");
            this.imgListEnemyAttack.Images.SetKeyName(21, "enemy_attack_hero_right_5.png");
            this.imgListEnemyAttack.Images.SetKeyName(22, "enemy_attack_hero_right_6.png");
            this.imgListEnemyAttack.Images.SetKeyName(23, "enemy_attack_hero_right_7.png");
            this.imgListEnemyAttack.Images.SetKeyName(24, "enemy_attack_hero_right_8.png");
            // 
            // imgHeroUnderDamage
            // 
            this.imgHeroUnderDamage.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgHeroUnderDamage.ImageStream")));
            this.imgHeroUnderDamage.TransparentColor = System.Drawing.Color.Transparent;
            this.imgHeroUnderDamage.Images.SetKeyName(0, "hero_under_light_attack_1.png");
            this.imgHeroUnderDamage.Images.SetKeyName(1, "hero_under_light_attack_2.png");
            this.imgHeroUnderDamage.Images.SetKeyName(2, "hero_under_light_attack_3.png");
            this.imgHeroUnderDamage.Images.SetKeyName(3, "hero_under_light_attack_4.png");
            this.imgHeroUnderDamage.Images.SetKeyName(4, "hero_under_light_attack_5.png");
            this.imgHeroUnderDamage.Images.SetKeyName(5, "hero_under_light_attack_6.png");
            this.imgHeroUnderDamage.Images.SetKeyName(6, "hero_under_light_attack_7.png");
            this.imgHeroUnderDamage.Images.SetKeyName(7, "hero_under_light_attack_8.png");
            this.imgHeroUnderDamage.Images.SetKeyName(8, "hero_under_light_attack_9.png");
            this.imgHeroUnderDamage.Images.SetKeyName(9, "hero_under_light_attack_death_1.png");
            this.imgHeroUnderDamage.Images.SetKeyName(10, "hero_under_light_attack_death_2.png");
            this.imgHeroUnderDamage.Images.SetKeyName(11, "hero_under_light_attack_death_3.png");
            this.imgHeroUnderDamage.Images.SetKeyName(12, "hero_under_light_attack_death_4.png");
            this.imgHeroUnderDamage.Images.SetKeyName(13, "hero_under_light_attack_10.png");
            this.imgHeroUnderDamage.Images.SetKeyName(14, "hero_under_strong_attack_1.png");
            this.imgHeroUnderDamage.Images.SetKeyName(15, "hero_under_strong_attack_2.png");
            this.imgHeroUnderDamage.Images.SetKeyName(16, "hero_under_strong_attack_3.png");
            this.imgHeroUnderDamage.Images.SetKeyName(17, "hero_under_strong_attack_4.png");
            this.imgHeroUnderDamage.Images.SetKeyName(18, "hero_under_strong_attack_5.png");
            this.imgHeroUnderDamage.Images.SetKeyName(19, "hero_under_strong_attack_6.png");
            this.imgHeroUnderDamage.Images.SetKeyName(20, "hero_under_strong_attack_7.png");
            this.imgHeroUnderDamage.Images.SetKeyName(21, "hero_under_strong_attack_8.png");
            this.imgHeroUnderDamage.Images.SetKeyName(22, "hero_under_strong_attack_9.png");
            this.imgHeroUnderDamage.Images.SetKeyName(23, "hero_under_strong_attack_10.png");
            this.imgHeroUnderDamage.Images.SetKeyName(24, "hero_under_strong_attack_11.png");
            this.imgHeroUnderDamage.Images.SetKeyName(25, "hero_under_strong_attack_12.png");
            this.imgHeroUnderDamage.Images.SetKeyName(26, "hero_under_strong_attack_13.png");
            this.imgHeroUnderDamage.Images.SetKeyName(27, "hero_under_strong_attack_14.png");
            this.imgHeroUnderDamage.Images.SetKeyName(28, "hero_under_strong_attack_15.png");
            this.imgHeroUnderDamage.Images.SetKeyName(29, "hero_under_strong_attack_16.png");
            this.imgHeroUnderDamage.Images.SetKeyName(30, "hero_under_strong_attack_death_1.png");
            this.imgHeroUnderDamage.Images.SetKeyName(31, "hero_under_strong_attack_death_2.png");
            // 
            // imgListEnemyStrongAttack
            // 
            this.imgListEnemyStrongAttack.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListEnemyStrongAttack.ImageStream")));
            this.imgListEnemyStrongAttack.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListEnemyStrongAttack.Images.SetKeyName(0, "enemy_attack_hero_down_1.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(1, "enemy_attack_hero_down_2.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(2, "enemy_attack_hero_down_3.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(3, "enemy_attack_hero_down_6.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(4, "enemy_attack_hero_up_1.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(5, "enemy_attack_hero_up_2.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(6, "enemy_attack_hero_up_4.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(7, "enemy_attack_hero_left_1.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(8, "enemy_attack_hero_left_2.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(9, "enemy_attack_hero_left_3.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(10, "enemy_attack_hero_left_5.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(11, "enemy_attack_hero_left_8.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(12, "enemy_attack_hero_right_1.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(13, "enemy_attack_hero_right_2.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(14, "enemy_attack_hero_right_3.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(15, "enemy_attack_hero_right_4.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(16, "enemy_attack_hero_right_5.png");
            this.imgListEnemyStrongAttack.Images.SetKeyName(17, "enemy_attack_hero_right_8.png");
            // 
            // imgHeroUseShovel
            // 
            this.imgHeroUseShovel.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgHeroUseShovel.ImageStream")));
            this.imgHeroUseShovel.TransparentColor = System.Drawing.Color.Transparent;
            this.imgHeroUseShovel.Images.SetKeyName(0, "hero_use_shovel_down_1.png");
            this.imgHeroUseShovel.Images.SetKeyName(1, "hero_use_shovel_down_2.png");
            this.imgHeroUseShovel.Images.SetKeyName(2, "hero_use_shovel_down_3.png");
            this.imgHeroUseShovel.Images.SetKeyName(3, "hero_use_shovel_up_1.png");
            this.imgHeroUseShovel.Images.SetKeyName(4, "hero_use_shovel_up_2.png");
            this.imgHeroUseShovel.Images.SetKeyName(5, "hero_use_shovel_up_3.png");
            this.imgHeroUseShovel.Images.SetKeyName(6, "hero_use_shovel_left_1.png");
            this.imgHeroUseShovel.Images.SetKeyName(7, "hero_use_shovel_left_2.png");
            this.imgHeroUseShovel.Images.SetKeyName(8, "hero_use_shovel_left_3.png");
            this.imgHeroUseShovel.Images.SetKeyName(9, "hero_use_shovel_right_1.png");
            this.imgHeroUseShovel.Images.SetKeyName(10, "hero_use_shovel_right_2.png");
            this.imgHeroUseShovel.Images.SetKeyName(11, "hero_use_shovel_right_3.png");
            // 
            // imgCoinValues
            // 
            this.imgCoinValues.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgCoinValues.ImageStream")));
            this.imgCoinValues.TransparentColor = System.Drawing.Color.Transparent;
            this.imgCoinValues.Images.SetKeyName(0, "coin_values_zero.png");
            this.imgCoinValues.Images.SetKeyName(1, "coin_values_one.png");
            this.imgCoinValues.Images.SetKeyName(2, "coin_values_two.png");
            this.imgCoinValues.Images.SetKeyName(3, "coin_values_three.png");
            this.imgCoinValues.Images.SetKeyName(4, "coin_values_four.png");
            this.imgCoinValues.Images.SetKeyName(5, "coin_values_five.png");
            this.imgCoinValues.Images.SetKeyName(6, "coin_values_six.png");
            this.imgCoinValues.Images.SetKeyName(7, "coin_values_seven.png");
            this.imgCoinValues.Images.SetKeyName(8, "coin_values_eight.png");
            this.imgCoinValues.Images.SetKeyName(9, "coin_values_nine.png");
            // 
            // imgWateringStump
            // 
            this.imgWateringStump.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgWateringStump.ImageStream")));
            this.imgWateringStump.TransparentColor = System.Drawing.Color.Transparent;
            this.imgWateringStump.Images.SetKeyName(0, "watering_stump_1.png");
            this.imgWateringStump.Images.SetKeyName(1, "watering_stump_2.png");
            this.imgWateringStump.Images.SetKeyName(2, "watering_stump_3.png");
            this.imgWateringStump.Images.SetKeyName(3, "watering_stump_4.png");
            this.imgWateringStump.Images.SetKeyName(4, "watering_stump_5.png");
            this.imgWateringStump.Images.SetKeyName(5, "watering_stump_6.png");
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1280, 1024);
            this.Cursor = System.Windows.Forms.Cursors.Default;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "RootsOfLife";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.Form1_Load);
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.Form1_Paint);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Form1_KeyDown);
            this.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Form1_KeyPress);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Timer timer_moving;
        private System.Windows.Forms.ImageList imageListSymbols;
        private System.Windows.Forms.Timer menu_timer;
        private System.Windows.Forms.ImageList imgListValues;
        private System.Windows.Forms.ImageList imgUI;
        private System.Windows.Forms.ImageList imgUI_EnergyPoints;
        private System.Windows.Forms.ImageList imgHeroValues;
        private System.Windows.Forms.ImageList imgListInventory;
        private System.Windows.Forms.ImageList imgListHeroWater;
        private System.Windows.Forms.ImageList imgListInterface;
        private System.Windows.Forms.ImageList imgListStone;
        private System.Windows.Forms.ImageList imgForBuilding;
        private System.Windows.Forms.ImageList imgListRoom;
        private System.Windows.Forms.ImageList imgListEnemy;
        private System.Windows.Forms.ImageList imageListGame;
        private System.Windows.Forms.ImageList imgListBow;
        private System.Windows.Forms.ImageList imgListItems;
        private System.Windows.Forms.ImageList imgListEnemyAttack;
        private System.Windows.Forms.ImageList imgHeroUnderDamage;
        private System.Windows.Forms.ImageList imgListEnemyStrongAttack;
        private System.Windows.Forms.ImageList imgHeroUseShovel;
        private System.Windows.Forms.ImageList imgCoinValues;
        private System.Windows.Forms.ImageList imgWateringStump;
    }
}

